language: python
python:
  - "3.6.5"
install:
  - pip install --upgrade pip && pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
script: 
  - pytest 

after_script:
  - coveralls

after_success:
  - codecov

