language: node_js
node_js:
- "stable"
cache:
  directories:
  - "node_modules"
before_script:
- npm i -g npm@version-number
script:
- npm start &
- npm test
after_success: 
- npm run coveralls
- coveralls
services:
- http-server


